8391256: TestZoneTextPrinterParser.java assertion fails with expected: <Mountain Standard Time> but was: <Mountain Daylight Time>
Reviewed-by: andrew, sgehwolf
Backport-of: 1fac148c2dcc5c2f065999ff3562a76e3c699d0f
(cherry picked from commit 92fcfff6486d67144c32c67ca4678a7e0b572f4e)